### ISSUE TITLE
Problems when training SPADE: There is always "RuntimeError: CUDA out of memory..."

### ISSUE THREAD

**Issue by Alive1024** [YingdaXia/SynthCP#5]
Hi @YingdaXia ,
Thanks for your great work! But I have met some problems, could you please help me? Thanks a lot!
I'm trying to train SPADE using **my** **own** **dataset** (1280*1280), when I start to train SPADE, there is always an error: "RuntimeError: CUDA out of memory...". As far as I know, I try to decrease batch size (even as small as the number of GPUs) and input size, but this didn't take effect. And I run it on another machine with 3x 2080Ti, but it's still the same. 
The error is like:
- (Machine 1)RuntimeError: `CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 4.00 GiB total capacity; 2.78 GiB already allocated; 14.61 MiB free; 112.69 MiB cached)`
- (Machine 2)RuntimeError: `CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 10.76 GiB total capacity; 9.73 GiB already allocated; 45.19 MiB free; 53.09 MiB cached)`

I found it's always 50.00 MiB...... Maybe there is something wrong with my parameters?
` python train.py --name sjd_1130 --dataset_mode sjd --no_instance --niter 60 --batchSize 3 --nThread 8 --no_html --gpu_ids 0,1,2`

The complete error log is:
```
Traceback (most recent call last):
  File "train.py", line 46, in <module>
    trainer.run_generator_one_step(data_i)
  File "....../SynthCP/trainers/pix2pix_trainer.py", line 36, in run_generator_one_step
    g_losses, generated, pred_seg = self.pix2pix_model(data, mode='generator')
  File "....../lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "....../lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "....../lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "....../lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "....../lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "....../lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "....../lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "....../SynthCP/models/pix2pix_model.py", line 59, in forward
    generator_input, real_image)
  File "....../SynthCP/models/pix2pix_model.py", line 212, in compute_generator_loss
    G_losses['VGG'] = self.criterionVGG(fake_image, real_image) \
  File "....../lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "....../SynthCP/models/networks/loss.py", line 110, in forward
    x_vgg, y_vgg = self.vgg(x), self.vgg(y)
  File "....../lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "....../SynthCP/models/networks/architecture.py", line 118, in forward
    h_relu2 = self.slice2(h_relu1)
  File "....../lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "....../lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "....../lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "....../lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 141, in forward
    self.return_indices)
  File "....../lib/python3.6/site-packages/torch/_jit_internal.py", line 134, in fn
    return if_false(*args, **kwargs)
  File "....../lib/python3.6/site-packages/torch/nn/functional.py", line 487, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 10.76 GiB total capacity; 9.73 GiB already allocated; 45.19 MiB free; 53.09 MiB cached) 
```

BTW, a suggestion: if there is an easy guide on how to train/finetune SynthCP on other datasets (how to input data correctly, which parameter should be paid attention to, etc), I think it will be of great help.

Thanks a lot!

**Comment by YingdaXia** [comment]
Hi @Alive1024 ,

Thanks for the interest and kind suggestions! 

As you know, our GAN training is based on SPADE, which could consume a lot of memory if you use the original resolution, such as 1280x1280 in your case. In the Cityscapes dataset, we train SPADE only in 512x256 resolution, which already produces good results for the "compare" step. For higher resolution training of the GAN, we strongly recommend you to refer to the original [SPADE repo](https://github.com/nvlabs/spade/) for details.

Thanks,
Yingda

**Comment by Alive1024** [comment]
@YingdaXia Thanks very much for your reply!
I have read something about SPADE. I have to say I didn't realize how memory-consuming SPADE is since I just know a little about GAN like that before. After setting the input size to 320x320 and use a machine with larger GPU memory, it works. Thanks again.
